# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Isomertic Contribution graph
on:
  schedule: [{cron: "0 5 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          output_action: none

          user: C10udburst
          template: classic
          base: ""
          base_skip: yes
          config_display: large
          config_timezone: Europe/Warsaw
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: Checkout data
        uses: actions/checkout@v2
        with:
          ref: data
          path: data
      - name: Move generated SVG to the proper path
        run: |
          sudo mv ./metrics_renders/*.svg ./data/iso-contributions.svg
      - name: Push data
        run: |
          cd data
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "chore(docs): Update iso contributions" || exit 0   # do not error if nothing to commit
          git push
